# Generated by Django 3.1.2 on 2020-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201009_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
