# Generated by Django 3.0.5 on 2020-10-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('cart', '0002_auto_20201016_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ManyToManyField(to='checkout.BillingAddress'),
        ),
    ]
