# Generated by Django 3.0.5 on 2020-11-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
